using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Threading.Tasks;
using Ai_Company.Options;
using Application.Service.Interfaces;
using Domain.Entitites;
using Google.Api.Gax.Grpc;   
using Microsoft.Extensions.Options;
using static Google.Api.Gax.Grpc.ClientHelper;
using System.Text.Json.Serialization;

namespace Application.Service
{

    public class GeminiService : IGeminiService
    {
        private readonly HttpClient _http;
        private readonly GeminiOptions _options;
        private const string ApiBaseUrl = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent";

        public GeminiService(HttpClient http, IOptions<GeminiOptions> options)
        {
            _http = http;
            _options = options.Value;
        }

        public async Task<string> GenerateContentAsync(List<Chat> history)
        {
            if (history == null || !history.Any())
            {
                throw new ArgumentException("Chat history (even for a single message) cannot be empty.");
            }

            var requestBody = new GeminiRequest
            {
                Contents = history.Select(m => new GeminiContent
                {
                    Role = m.Role,
                    Parts = new[] { new GeminiPart { Text = m.Text } }.ToList()
                }).ToList()
            };



            var json = JsonSerializer.Serialize(requestBody, new JsonSerializerOptions { WriteIndented = false });
            var content = new StringContent(json, Encoding.UTF8, "application/json");

            var requestUri = $"{ApiBaseUrl}?key={_options.ApiKey}";
            var response = await _http.PostAsync(requestUri, content);

            response.EnsureSuccessStatusCode();

            var responseString = await response.Content.ReadAsStringAsync();

            try
            {
                var geminiResponse = JsonSerializer.Deserialize<GeminiResponse>(responseString);

                var generatedText = geminiResponse?.Candidates?
                                                 .FirstOrDefault()?
                                                 .Content?
                                                 .Parts?
                                                 .FirstOrDefault()?
                                                 .Text;

                if (string.IsNullOrEmpty(generatedText))
                {
                    return "No response generated by Gemini.";
                }

                return generatedText;
            }
            catch (JsonException ex)
            {
                Console.WriteLine($"JSON parsing error: {ex.Message}");
                Console.WriteLine($"Raw Gemini response: {responseString}");
                throw new InvalidOperationException("Failed to parse Gemini API response.", ex);
            }
        } 
        public class GeminiRequest
        {
            [JsonPropertyName("contents")]
            public List<GeminiContent> Contents { get; set; } = new List<GeminiContent>();
        }

        public class GeminiContent
        {
            [JsonPropertyName("role")]
            public string Role { get; set; }

            [JsonPropertyName("parts")]
            public List<GeminiPart> Parts { get; set; } = new List<GeminiPart>();
        }

        public class GeminiPart
        {
            [JsonPropertyName("text")]
            public string Text { get; set; }
        }

        public class GeminiResponse
        {
            [JsonPropertyName("candidates")]
            public List<GeminiCandidate>? Candidates { get; set; }
        }

        public class GeminiCandidate
        {
            [JsonPropertyName("content")]
            public GeminiContent? Content { get; set; }
        }

        // --- Internal Chat Message DTO (simplified, ConversationId not strictly needed for stateless) ---
        public class Chat
        {
            public string Role { get; set; } // "user" or "model"
            public string Text { get; set; }
        }
    }
}